### ISSUE TITLE
UX: Larger map view

### ISSUE THREAD

**Issue by hastebrot** [abrenaut/posio#2]
Here are some quick ideas for the UI.

- Increase the size of the world map (theater or panorama view).
- Move the highscore list to a sidebar on the right.
- Change mercator projection the something different (maybe Miller projection, greenland is very huge in web mercator). But seems we should keep the projection equirectangular. Or at least change the default zoom to only include the top of canada/alaska/sweden and the bottom of chile/argentina/new zealand.

**Comment by abrenaut** [comment]
The width of the map has been increased and the leaderboard moved to the right.
