### ISSUE TITLE
Any alternative live versions of this game?

### ISSUE THREAD

**Issue by austinhuang0131** [abrenaut/posio#8]
Since your domain is gone already

**Comment by isidentical** [comment]
You can check out [my fork's live demo](http://45.32.238.245/posio/). I ported it to py3 and pipenv also removed country hint, [fork](https://github.com/isidentical/posio)

**Comment by worldworm** [comment]
Is the domain officially dead?

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by isidentical** [comment]
I'm deleting my fork in favor of built-in python3 compatibility.

**Comment by abrenaut** [comment]
Fixed the live version!
